name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install all the packages"
        run: npm ci
      - name: "Build all the packages"
        run: npm run build
      - name: "Validate all the packages"
        run: npm run validate
